[package]
name = "hexdump"
authors = ["aDodge"]
version = "0.1.0"
edition = "2024"

[dependencies]
colored = "3.0.0"
windows-sys = { version = "0.60.2", features = ["Win32_System_Console"] }
clap = { version = "4.5.45", features = ["derive"] }
